import type { Metadata } from "next";
import { Recursive } from "next/font/google";
import "../shared/styles/globals.css";
import Providers from "@/shared/utils/Providers";
import { ClerkProvider } from "@clerk/nextjs";

const recursive = Recursive({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={recursive.className}>
          <Providers>{children}</Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
